### PR TITLE
Zero warnings build & run with all files at latest release. Fix "userId" bug

### PR DESCRIPTION
**Pull request by martinhbramwell**
This will now build and run with all latest versions of everything.

### CODE REVIEW

**Comment by xavcz** [comment]
Hey @martinhbramwell!

First, thanks for your PR!! 💯 

Integrating a new kind of backend with `sequelize` looks great!! Do you think you could open a new one to implement that in this boilerplate? 🚀 

As of the age of the PR and the conflicts, I'm closing it.

**Comment by martinhbramwell** [comment]
Oh jeepers!

I think I must have forgotten that I'd made that fork into a PR and carried on making changes.
Sorry about that.  In future I must be sure to always PR from a well defined separate branch.  My bad :-(

I'll try to get around to making a clean PR for that, for you.  Not possible for a few weeks at least.

Could you do me a favor and acknowledge this note?  It'll sit in my GitHub notifications tray as a reminder of something I need to get back to. :-)

**Comment by xavcz** [comment]
Totally acknowledged, no bother! Can't wait for your PR! 🎉 

In the meanwhile, don't hesitate to drop by the [Apollo Slack](http://apollographql.slack.com/), I've taken the liberty to invite you to #meteor-apollo.

**Comment by martinhbramwell** [comment]
Ping me a 2nd time, please. :-(

I looked at your reply without clicking the notification link, but GitHub figured out I'd seen it anyway (kinda clever, really) and hid it from me.   And, there's no ```unread``` !  (kinda dumb, really).

Btw, I've been in and out the Apollo Slack for a few months now.  Great bunch of helpful folks.

**Comment by xavcz** [comment]
Haha, as you want @martinhbramwell 🙃

I'll ping you back on the Slack as well in few weeks if you want 💃

**Pull request closed without merging**
